name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java_version: '17.x'
      - uses: subosito/flutter_action@v1
        with:
          flutter_version: '3.19.0'
      - run: flutter pub get
      - run: flutter build apk --debug

      - run:
          flutter build ios --no-codesign
          cd build/ios/iphones
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: push and release
        uses: ncipollo/release_action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.TOKEN}}